export const SUCCESS = 'success';
export const FAIL = 'fail';

export const PERMISSION_READ = 'READ';
export const PERMISSION_WRITE = 'WRITE';
export const PERMISSION_DELETE = 'DELETE';
export const PERMISSION_SHARE = 'SHARE';
export const PERMISSION_UPLOAD_FILES = 'UPLOAD_FILES';

export const PERMISSIONS = [
  PERMISSION_READ,
  PERMISSION_WRITE,
  PERMISSION_DELETE,
  PERMISSION_SHARE,
  PERMISSION_UPLOAD_FILES
];
